services:
  vision_foundation_models:
    build:
      context: .
      dockerfile: Dockerfile
    image: frostlab/vision_foundation_models:cu129
    container_name: vision_foundation_models_dev
    stdin_open: true
    tty: true
    ipc: host
    shm_size: '8gb'
    volumes:
      # Mount workspace directory into /workspace inside container
      - ./workspace:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - DISPLAY=${DISPLAY}
    working_dir: /workspace