services:
  vision_foundation_models:
    build:
      context: .
      dockerfile: Dockerfile
    image: vision_foundation_models:latest
    container_name: vision_foundation_models_dev
    stdin_open: true
    tty: true
    ipc: host
    shm_size: '8gb'
    runtime: nvidia
    volumes:
      - ./workspace:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY:-:0}
    working_dir: /workspace